<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Models\"/>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.6"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.6"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.6">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="bodong.Avalonia.PropertyGrid" Version="11.3.3.2" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="ElectricFox.ConfigManagement" Version="1.2.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="ReactiveUI" Version="22.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ElectricFox.Epaper.Data\ElectricFox.Epaper.Data.csproj" />
      <ProjectReference Include="..\ElectricFox.Epaper.Rendering\ElectricFox.Epaper.Rendering.csproj" />
      <ProjectReference Include="..\ElectricFox.Epaper.Sockets\ElectricFox.Epaper.Sockets.csproj" />
    </ItemGroup>
</Project>
